### ISSUE TITLE
USB Hard Drives

### ISSUE THREAD

**Issue by OrakMoya** [r-darwish/alma#24]
I have a 320GB external hard drive and I wanted to use it for a portable arch installation.
The configuration for decreased writes to the USB sounded nice since the HDD is connected with a micro USB cable, as well as the ability to boot on both UEFI and BIOS systems.

But when I tried to create it refused to wipe the HDD and install arch linux on it.

Is there an option to wipe and install anyways?

**Comment by r-darwish** [comment]
USB HDDs aren't considered removable in Linux. I'll add a flag to allow installation on non removable devices
