### ISSUE TITLE
option to start with mounting filesystems in alma create

### ISSUE THREAD

**Issue by sharethewisdom** [r-darwish/alma#27]
Would it be useful to users to be able to resume `alma create` from the mount step?

I have problems with a specific usb key: (1) mounting the ext4 filesystem _error loading journal_, and an _invalid backup GPT header_" issue (2).

**More info on my specific problem:**

I wiped and formatted the usb key manually, fixed problem (2) manually in the recovery & transformation menu from gdisk to overwrite the GPT backup.

I reached out for help twice on the [Arch linux forums](https://bbs.archlinux.org/viewtopic.php?id=253354), ([first post](https://bbs.archlinux.org/viewtopic.php?id=253352)) but immediately got rejected and then called a liar. I was able to create fat and ext4 filesystems without errors. But mounting the ext4 partition (/dev/sdc3) still failed. I also successfully ran `e2fsck -fp /dev/sdc3`, but to no avail. Every time it keeps reporting _Superblock has an invalid journal (inode 8)_. I know this isn't a forum, but 'll be thankful if you help me solve the issue in some way. I tried to remove journalling from the ext4 filesystem, which gave me this error:

```
# tune2fs -O '^has_journal' /dev/sdc3
tune2fs 1.45.5 (07-Jan-2020)
tune2fs: Block bitmap checksum does not match bitmap while reading bitmaps
```

alma version: 0.10.0

Linux 5.5.7-arch1-1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux

**Comment by r-darwish** [comment]
If you have problems with a specific USB key then I suggest replacing it.
