### ISSUE TITLE
not working in Manjaro

### ISSUE THREAD

**Issue by yananet** [r-darwish/alma#32]
Hello

thank you for the great tool.
I am not sure whether manjaro is supported or not anyway it is not working with my manjaro laptop
```
Generating locales...
  en_US.UTF-8... done
Generation complete.
 2020-03-17 07:45:16 INFO  alma > Generating initramfs
/usr/bin/mkinitcpio: line 265: /etc/mkinitcpio.d/linux.preset: No such file or directory
==> ERROR: Failed to load preset: `/etc/mkinitcpio.d/linux.preset'
 2020-03-17 07:45:22 ERROR alma > Initramfs error
 2020-03-17 07:45:22 ERROR alma > Caused by: exit code: 1
```

**Comment by r-darwish** [comment]
I don't officially support Manjaro. However, this looks like #31 so it's probably an Arch Linux issue as well, so I'm closing this as duplicate

**Comment by yananet** [comment]
FYI
was worked in my Arch desktop.

**Comment by jamesmcm** [comment]
Hopefully #36 will fix this, please test it.
