### ISSUE TITLE
Package as deb and rpm for other distributions

### ISSUE THREAD

**Issue by jamesmcm** [r-darwish/alma#39]
## Task
We should package ALMA for other distributions - rpm and deb being the main targets (Fedora, Ubuntu, Debian, etc.)

This can probably be achieved using the dockerfile (or perhaps even with just LXC or chroots if they are on a Linux system).

## Justification

Users will be able to create an Arch Linux image with ALMA,  without using Arch Linux beforehand.

**Comment by r-darwish** [comment]
ALMA depends on the Arch installation scripts and pacman. Is there any way to install these on distributions other than Arch?
