### ISSUE TITLE
Add command to run shellcheck on custom scripts in given preset files

### ISSUE THREAD

**Issue by jamesmcm** [r-darwish/alma#41]
## Task

Add a new command to ALMA to run [shellcheck](https://github.com/koalaman/shellcheck) on the custom scripts in all given presets.

Note that shellcheck does not need the environment variables references in the scripts to be set.

## Justification

This will make it easier for preset developers and users to debug any custom scripts in their presets.

**Comment by r-darwish** [comment]
Sorry, but this one is out of the tool's scope. When you develop your preset script then you're responsible for choosing your development and testing tools.
