### ISSUE TITLE
Create preset example for Secure Boot

### ISSUE THREAD

**Issue by jamesmcm** [r-darwish/alma#44]
## Task

Create a preset file that works for booting with Secure Boot enabled.

Or we could override the boot loader directly in this case.

See: https://wiki.archlinux.org/index.php/Secure_Boot#Using_a_signed_boot_loader for details

## Justification

Would allow an ALMA-created USB to boot on even more machines (i.e. when we can't disable Secure Boot).

**Comment by r-darwish** [comment]
Actually I rather change the tool itself so that it supports secure boot as well. Sadly I don't have the hardware to test it or the knowledge to do that, so help is welcome.

**Comment by r-darwish** [comment]
@jamesmcm do you have the hardware to test it? Can you take an existing ALMA image and manually install PreLoader and test that it's working? If it does, then I think we can always install preload in ALMA so there won't be any need to using a preset just to enable secure boot, but I will need someone to test it out.

**Comment by jamesmcm** [comment]
Sure, I'll try it when I get some time in December. I'll need to re-enable the Secure Boot keys and make sure I can boot my main system 🙂
