### ISSUE TITLE
Add flag to specify target partition rather than reformatting whole disk

### ISSUE THREAD

**Issue by jamesmcm** [r-darwish/alma#46]
## Task

A flag should be added to specify the target partition, instead of formatting the entire disk.

The partition itself could be reformatted.

Full disk encryption should not be allowed in this case, bootloader installation should be optional as a separate flag.

## Justification

This is useful if installing to a device you are already using, i.e if you have some UDF or NTFS partitions that you want to keep.

**Comment by r-darwish** [comment]
In this way there's nothing that will take care in setting up Grub so you'll have to do it manually. If you need to perform manual steps to handle booting then I don't think you should use ALMA, but instead just perform manual installation.
