### ISSUE TITLE
Increase default size of boot partition

### ISSUE THREAD

**Issue by viktorbahr** [r-darwish/alma#50]
Hi :)
I love the tool @r-darwish, saves me loads of time - many thanks for sharing!

I did however came across a default setting where I see some room for improvement: The size of the boot partition.
In my example setup 78M out of 100M of the boot partition are occupied after the installation. This means that I won't be able to place any additional boot images like `linux-lts` on there without having to resize both the root and boot partition.

I would thus suggest to increase the default size of the boot partition to support setting up multiple boot images without the need to touch the partition table again.

In my example the boot partition content grew to 159M after setting up `linux-lts`, an increase of 81M compared to the original state. My personal preference would be to support up to 2 additional boot options. A default size of **250M** should cover this.

What do you think?

P.S.: Ideally, I'd make the partition sizes user-configurable. Maybe as additional command line arguments to the `alma create` command? Will try to prepare an example in my fork.

**Comment by jamesmcm** [comment]
Sounds good, did you start work on this?

The line to change is: https://github.com/r-darwish/alma/blob/c8b151fe5ff5abe18a091e78567f3ed84c7470d5/src/main.rs#L187

You can see an example of an argument using the Bytes type (so the user can enter MB, MiB, KB, etc.) here:  https://github.com/r-darwish/alma/blob/c8b151fe5ff5abe18a091e78567f3ed84c7470d5/src/args.rs#L68
see the `parse_bytes()` function at the top too.

So I'd recommend adding an argument that is Option<Byte> and then when it is None set it to 250MB. Also please update the readme as it'll affect the viable minimum image size, but I think it makes sense overall.
