### ISSUE TITLE
Does not detect drive when addressed as /dev/sdb

### ISSUE THREAD

**Issue by KSPAtlas** [r-darwish/alma#69]
**Describe the bug** 
When I try to put Arch on a USB stick using ALMA I get an error that /dev/sdb is not a binary path.

**To Reproduce**
Try to install by using /dev/sdX

**Expected behavior**
I would expect it to work because it is still a block device file.

**Additional context**
The USB is 8gb and formatted as ext4.

EDIT: It does not work for any path at all

**Comment by r-darwish** [comment]
What's the exact command that you're trying to run?

**Comment by Charterino** [comment]
Run this:
sudo pacman -S gptfdisk
