### ISSUE TITLE
Hardware abilities

### ISSUE THREAD

**Issue by samrod8** [r-darwish/alma#70]
after install a distribution on a USB drive it's run well on my generic machine, but when i move to a HP machine  it's frezze, The USB drive need a configuration, i know the grub could be wrong. but how i make my USB alma avail to any hardware? 

**Describe the solution you'd like**
i will like to know some configuration or software to avail USB alma to boot in any hardware.

**Describe alternatives you've considered**
i check the drives of Nvidia but also check the grub and it's not works.

**Additional context**
my USB alma boots in a intel machine but no in a amd machine

how does the developer avail a liveUSB to boot in the right config base in a hardware machine?

**Comment by r-darwish** [comment]
I don't think I did anything intel-specific so I cannot tell whether you have some issue specific to your machine, or a general issue with AMD. If you can tell exactly why doesn't your machine boot and what needs to be done in order to make it bootable then please reopen this issue.
