### ISSUE TITLE
 Unable to umount /tmp/.tmphFl1yt: EBUSY: Device or resource busy Error: Failed to build AUR helper  

### ISSUE THREAD

**Issue by arnav7633** [r-darwish/alma#73]
I am just unable to make a USb No flags no arguments was given when the command was ran

I am using a distro of arch linux
```
2021-07-20T12:42:41.916Z WARN  alma::storage::mount_stack > Unable to umount /tmp/.tmphFl1yt: EBUSY: Device or resource busy
Error: Failed to build AUR helper

Caused by:
Bad exit code: exit status: 8
```

**Comment by r-darwish** [comment]
* Does something interesting appear in `dmesg` after this error?
* Does it work on another USB device?
* Does it work when trying to create a local image?
