### ISSUE TITLE
[Failed] ALMA failing to create persistent USB off EndevourOS.

### ISSUE THREAD

**Issue by HarshalRathore** [r-darwish/alma#81]
## Host OS
EndevourOS with i3+KDE+GNOME

## Command executed
`ALMA_USER="harshal" TIMEZONE="Asia/Kolkata" sudo -E alma create --presets ./arch-i3-usb/preset`

<details>
<summary>Error</summary>
<pre>Generation complete.
 2021-12-03T14:28:43.569Z INFO  alma              > Installing AUR packages
Cloning into '/home/aur/yay'...
remote: Enumerating objects: 352, done.
remote: Counting objects: 100% (352/352), done.
remote: Compressing objects: 100% (245/245), done.
remote: Total 352 (delta 105), reused 336 (delta 105), pack-reused 0
Receiving objects: 100% (352/352), 79.06 KiB | 268.00 KiB/s, done.
Resolving deltas: 100% (105/105), done.
==> Making package: yay-bin 11.0.2-1 (Fri Dec  3 14:28:49 2021)
==> Checking runtime dependencies...
error: config file /etc/pacman.d/endeavouros-mirrorlist could not be read: No such file or directory
==> ERROR: 'pacman' returned a fatal error (1):
Error: Failed to build AUR helper

Caused by:
    Bad exit code: exit status: 8</pre>
</details>

## Presets
[Presets File](https://github.com/jamesmcm/arch-i3-usb)

## What I already tried.
- Checked for `/etc/pacman.d/endeavouros-mirrorlist` it is there in my system.
- My system is up to date( `# pacman -Syu` ), nothing is broken in it.
- Only solution I could come up with is temporarily removing that particular file and EndevourOS repository entry in `pacman.conf`. But I don't want to mess with any file whose removing, moving requires `sudo` privileges.

I request you to look in to it @r-darwish.
Thank you.

**Comment by r-darwish** [comment]
https://github.com/r-darwish/alma#using-arch-linux-derivatives

Alma isn't supported on Arch derivatives.
