### ISSUE TITLE
bash: ./alma: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by CorruptedPlazma** [r-darwish/alma#83]
**Describe the bug** 
Returns error `cannot execute binary file: Exec format error` when attempting to run ALMA. 

**To Reproduce**
1. Install ALMA from the AUR or this github
2. Attempt to execute
3. Bash returns the error mentioned above

**Expected behavior**
Proper execution

**Additional context**
From a search on google this appears to be an issue with mismatched system architectures, but I'm running Arch Linux on an x86_64 CPU. That said, the program ran fine on another system with an older x86_64 CPU. I'm using packages updated about 3-4 days ago, and KDE Plasma as my DE.

**Comment by r-darwish** [comment]
Something is probably corrupted in your installation. Please try to reinstall
